// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rjtnuouffssxuvhverum.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJqdG51b3VmZnNzeHV2aHZlcnVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1Njk5MjAsImV4cCI6MjA2ODE0NTkyMH0.rJCCSHnQsMUwzbzb9bUVSSiOYSj-ffU41W5SR5pisqc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});